<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-16T01:16:14 AST" name="CVB Portal" finished-at="2023-06-16T01:16:17 AST" duration-ms="2401">
    <groups>
    </groups>
    <test started-at="2023-06-16T01:16:14 AST" name="Regression Test" finished-at="2023-06-16T01:16:17 AST" duration-ms="2401">
      <class name="Tests.login_module_Test">
        <test-method is-config="true" signature="startdriver()[pri:0, instance:Tests.login_module_Test@117159c0]" started-at="2023-06-16T01:16:05 AST" name="startdriver" finished-at="2023-06-16T01:16:14 AST" duration-ms="9126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startdriver -->
        <test-method signature="Admin_can_login_successfully()[pri:0, instance:Tests.login_module_Test@117159c0]" started-at="2023-06-16T01:16:15 AST" name="Admin_can_login_successfully" finished-at="2023-06-16T01:16:17 AST" duration-ms="2173" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Tests.login_module_Test.Admin_can_login_successfully(login_module_Test.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Admin_can_login_successfully -->
        <test-method is-config="true" signature="screenshotonfailure(org.testng.ITestResult)[pri:0, instance:Tests.login_module_Test@117159c0]" started-at="2023-06-16T01:16:17 AST" name="screenshotonfailure" finished-at="2023-06-16T01:16:17 AST" duration-ms="192" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Admin_can_login_successfully status=FAILURE method=login_module_Test.Admin_can_login_successfully()[pri:0, instance:Tests.login_module_Test@117159c0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotonfailure -->
        <test-method is-config="true" signature="stopdriver()[pri:0, instance:Tests.login_module_Test@117159c0]" started-at="2023-06-16T01:16:17 AST" name="stopdriver" finished-at="2023-06-16T01:16:17 AST" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopdriver -->
      </class> <!-- Tests.login_module_Test -->
    </test> <!-- Regression Test -->
  </suite> <!-- CVB Portal -->
</testng-results>
